# This is a default config file for bottom.  All of the settings are commented
# out by default; if you wish to change them uncomment and modify as you see
# fit.

# This group of options represents a command-line flag/option.  Flags explicitly
# added when running (ie: btm -a) will override this config file if an option
# is also set here.

[flags]
hide_avg_cpu = false
dot_marker = false
rate = "500ms"
cpu_left_legend = true
current_usage = false
unnormalized_cpu = false
group_processes = true
case_sensitive = false
whole_word = false
regex = true
default_time_value = "60s"
hide_time = false
default_widget_type = "proc"
default_widget_count = 1
# expanded_on_startup = false
# hide_table_gap = false
battery = true
disable_click = false
tree = true
show_table_scroll_position = true
process_command = true
# enable_gpu_memory = true
enable_cache_memory = true
retention = "10m"

[processes]
columns = ["pid", "name", "cpu%", "mem%", "State"]

# These are all the components that support custom theming.  Note that colour support
# will depend on terminal support.

#[colors] # Uncomment if you want to use custom colors
# Represents the colour of table headers (processes, CPU, disks, temperature).
#table_header_color="LightBlue"
# Represents the colour of the label each widget has.
#widget_title_color="Gray"
# Represents the average CPU color.
#avg_cpu_color="Red"
# Represents the colour the core will use in the CPU legend and graph.
#cpu_core_colors=["LightMagenta", "LightYellow", "LightCyan", "LightGreen", "LightBlue", "LightRed", "Cyan", "Green", "Blue", "Red"]
# Represents the colour RAM will use in the memory legend and graph.
#ram_color="LightMagenta"
# Represents the colour SWAP will use in the memory legend and graph.
#swap_color="LightYellow"
# Represents the colour ARC will use in the memory legend and graph.
#arc_color="LightCyan"
# Represents the colour the GPU will use in the memory legend and graph.
#gpu_core_colors=["LightGreen", "LightBlue", "LightRed", "Cyan", "Green", "Blue", "Red"]
# Represents the colour rx will use in the network legend and graph.
#rx_color="LightCyan"
# Represents the colour tx will use in the network legend and graph.
#tx_color="LightGreen"
# Represents the colour of the border of unselected widgets.
#border_color="Gray"
# Represents the colour of the border of selected widgets.
#highlighted_border_color="LightBlue"
# Represents the colour of most text.
#text_color="Gray"
# Represents the colour of text that is selected.
#selected_text_color="Black"
# Represents the background colour of text that is selected.
#selected_bg_color="LightBlue"
# Represents the colour of the lines and text of the graph.
#graph_color="Gray"
# Represents the colours of the battery based on charge
#high_battery_color="green"
#medium_battery_color="yellow"
#low_battery_color="red"

# Layout - layouts follow a pattern like this:
# [[row]] represents a row in the application.
# [[row.child]] represents either a widget or a column.
# [[row.child.child]] represents a widget.
#
# All widgets must have the type value set to one of ["cpu", "mem", "proc", "net", "temp", "disk", "empty"].
# All layout components have a ratio value - if this is not set, then it defaults to 1.
# The default widget layout:
[[row]]
  ratio=2
  [[row.child]]
  type="cpu"
[[row]]
    ratio=3
    [[row.child]]
      ratio=6
      type="mem"
    [[row.child]]
      ratio=4
      type="net"
[[row]]
  ratio=5
  [[row.child]]
    ratio=6
    type="proc"
    default=true
  [[row.child]]
    ratio=4
    [[row.child.child]]
      type="disk"
    [[row.child.child]]
      type="temp"


# Filters - you can hide specific temperature sensors, network interfaces, and disks using filters.  This is admittedly
# a bit hard to use as of now, and there is a planned in-app interface for managing this in the future:
#[disk_filter]
#is_list_ignored = true
#list = ["/dev/sda\\d+", "/dev/nvme0n1p2"]
#regex = true
#case_sensitive = false
#whole_word = false

#[mount_filter]
#is_list_ignored = true
#list = ["/mnt/.*", "/boot"]
#regex = true
#case_sensitive = false
#whole_word = false

#[temp_filter]
#is_list_ignored = true
#list = ["cpu", "wifi"]
#regex = false
#case_sensitive = false
#whole_word = false

#[net_filter]
#is_list_ignored = true
#list = ["virbr0.*"]
#regex = true
#case_sensitive = false
#whole_word = false

[colors]
table_header_color = "#f4dbd6"
all_cpu_color = "#f4dbd6"
avg_cpu_color = "#ee99a0"
cpu_core_colors = ["#ed8796","#f5a97f","#eed49f","#a6da95","#7dc4e4","#c6a0f6"]
ram_color = "#a6da95"
swap_color = "#f5a97f"
rx_color = "#a6da95"
tx_color = "#ed8796"
widget_title_color = "#f0c6c6"
border_color = "#5b6078"
highlighted_border_color = "#f5bde6"
text_color = "#cad3f5"
graph_color = "#a5adcb"
cursor_color = "#f5bde6"
selected_text_color = "#181926"
selected_bg_color = "#c6a0f6"
high_battery_color = "#a6da95"
medium_battery_color = "#eed49f"
low_battery_color = "#ed8796"
gpu_core_colors = ["#7dc4e4","#c6a0f6","#ed8796","#f5a97f","#eed49f","#a6da95"]
arc_color = "#91d7e3"
