# Global mise config.

[settings]

# Compiling from scratch (when applicable) is recommended on NixOS and Alpine.
# Otherwise, disable this to use pre-build binaries.
all_compile = true

experimental = true

gpg_verify = true

prefer_offline = true

# paranoid = false

# url_replacements = {}

[settings.python]
compile = false

[tools]
# Core tools:
bat = "latest"
eza = "latest"
helix = "latest"
jujutsu = "latest"
"conda:make" = "latest"
"aqua:tmux/tmux-builds" = "latest"

# Core utilities
atuin = "latest"
bottom = "latest"
delta = "latest"
difftastic = "latest"
"cargo:elio" = "latest"
jq = "latest"
"cargo:mergiraf" = "latest"
ripgrep = "latest"
"pipx:tmuxp" = "latest"
yazi = "latest"
yq = "latest"
zoxide = "latest"

# Advanced utilities:
"cargo:biff-datetime-cli" = "latest"
"cargo:cargo-zigbuild" = "latest"
"cargo:cfait" = "latest"
d2 = "latest"
# dig = "latest"
dua = "latest"
dust = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
# gh = "latest"
hexyl = "latest"
just = "latest"
lnav = "latest"
"cargo:onefetch" = "latest"
rclone = "latest"
ripgrep-all = "latest"
"cargo:scooter" = "latest"
sd = "latest"
"cargo:slipstream-cli" = "latest"
starship = "latest"
# "cargo:starship-jj" = "latest"
"cargo:swpui" = "latest"
"cargo:tealdeer" = "latest"
"cargo:tokei" = "latest"
typst = "latest"
typstyle = "latest"
viddy = "latest"
"pipx:yt-dlp" = "latest"
"cargo:zk-cli" = "latest"

# Platforms:
uv = "latest"
zig = "latest"
rust = "latest"
python = "latest"
ruff = "latest"

# Language support:
harper-ls = "latest"
marksman = "latest"
ty = "latest"

# "cargo:ouch" = "latest"

# Some core tools need to be istalled via the package manager:
# bash, fish, git, tree, mosh, wget, zip, unzip
# colordiff, file, gnupg, kbd, xdg-utils
# nitch, slides, yt-dlp
# systemctl-tui, procs, fselect
# ouch,
# ltex-ls, 

# Deps:
usage = "latest"
watchexec = "latest"
cargo-binstall = "latest"

[tools."http:cha"]
url = "https://git.sr.ht/~bptato/chawan/refs/download/v0.4.2/chawan-0-4-2-linux-amd64.tar.xz"
version = "0.4.2"
bin_path = "chawan-0-4-2-linux-amd64"
checksum = "sha256:f1f7e07a3eb6439e14e08f3913cdd8fc94861621b0af79c4b9cf1f1080071051"

# [tools."http:radicle"]
# url = "https://files.radicle.xyz/releases/latest/radicle-1.8.0-x86_64-unknown-linux-musl.tar.xz"
# version = "1.8.0"
# bin_path = "radicle-1.8.0-x86_64-unknown-linux-musl/bin"
# checksum = "sha256:c6cf18a44d64182270bfcfcb70a19bc1556e8627bcd6d3b6d373fe7e1c461cc2"
[tools."http:radicle"]
url = "https://files.radicle.dev/releases/latest/radicle-1.9.1-x86_64-unknown-linux-musl.tar.xz"
version = "1.9.1"
bin_path = "radicle-1.9.1-x86_64-unknown-linux-musl/bin"
checksum = "sha256:9374872f98d7497bfab631ba0113e3864b9916f8f56da0d1e52c0fc5b31b95f3"

# [tools."http:yubico-piv-tool"]
# url = "https://developers.yubico.com/yubico-piv-tool/Releases/yubico-piv-tool-2.7.3.tar.gz"
# version = "2.7.3"
# bin_path = ""
# checksum = "sha256:"

[tasks.edit]
description = "Edit the global mise config."
run = "$EDITOR ~/.config/mise/config.toml"
