import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "HackGen35 Console NF"
style = "Bold"

[font.bold_italic]
family = "M PLUS 1 Code"
style = "SemiBold"

[font.italic]
family = "M PLUS 1 Code"
style = "Regular"

[font.normal]
family = "HackGen35 Console NF"
style = "Regular"

[shell]
args = ["-c", "tmux new-session -A -s main"]
program = "fish"

[window]
dynamic_padding = true
startup_mode = "Maximized"

[window.dimensions]
columns = 80
lines = 24
