#
# aerc main configuration

[ui]
index-format=%D %-17.17n %s
timestamp-format=2006-01-02 03:04 PM
sidebar-width=20
empty-message=(no messages)
empty-dirlist=(no folders)
border-char-vertical="│"
border-char-horizontal="─"
styleset-name=catppuccin-mocha
mouse-enabled=true

[viewer]
pager=bat -l markdown
alternatives=text/plain,text/html
show-headers=false

[compose]
editor=hx

[filters]
#
# Filters allow you to pipe an email body through a shell command to render
# certain emails differently, e.g. highlighting them with ANSI escape codes.
#
# The first filter which matches the email's mimetype will be used, so order
# them from most to least specific.
#
# You can also match on non-mimetypes, by prefixing with the header to match
# against (non-case-sensitive) and a comma, e.g. subject,text will match a
# subject which contains "text". Use header,~regex to match against a regex.
# subject,~^\[PATCH=awk -f @SHAREDIR@/filters/hldiff
# text/*=awk -f @SHAREDIR@/filters/plaintext
#text/html=@SHAREDIR@/filters/html
#image/*=catimg -w $(tput cols) -
text/plain = colorize
#text/html = html | colorize
#text/html = ! w3m -I utf8 -T text/html
text/html=w3m -T text/html -dump -o display_link_number=1 | colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
