.TH "GIT\-REMOTE\-RAD" "1" "2024-11-28" "rad 0.8.0" "Radicle CLI Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
git-remote-rad \- Git remote helper for Radicle
.SH "SYNOPSIS"
.sp
\fBgit\-remote\-rad\fP *
.SH "DESCRIPTION"
.sp
\fBgit\-remote\-rad\fP is a \fBgit\fP(1) remote helper program to allow git
to interact with the local Radicle storage. git will use this program
automatically, when using a remote repository with the "rad" protocol.
It is never invoked directly.
.SH "SEE ALSO"
.sp
\fBgit\-remote\-helpers\fP(1), \fBrad\fP(1)
.SH "AUTHOR"
.sp
The Radicle Team