freq = "2hours"
log = "/tmp/slipknot.log"
storage = 4096

# Settings that apply to **everything**.
[global]

[global.filters]
exclude-title-words = [
  "sports",
  "football",
  "nfl",
  "basketball",
]
exclude-substrings = [
  "trump",
  "musk",
]

[global.options]
# Maximum feeds returned, something sane
max = 512
# 1 month in seconds
oldest = "1month"

# Settings that apply to the all feed.
[all]
exclude-title-words = [
]

# Feed definitions.
[feeds]

## News

[feeds.guardian-us]
url = "https://www.theguardian.com/us/rss"
tags = ["news"]

[feeds.npr-national]
url = "https://feeds.npr.org/1003/rss.xml"
tags = ["news"]
exclude-content-words = ["trump", "biden", "nfl", "sports", "football", "basketball"]

[feeds.npr-world]
url = "https://feeds.npr.org/1004/rss.xml"
tags = ["news"]
exclude-content-words = ["trump", "biden", "nfl", "sports", "football", "basketball"]

[feeds.conversation-politics]
url = "https://theconversation.com/us/politics/articles.atom"
tags = ["news"]

[feeds.japan-times]
url = "https://www.japantimes.co.jp/news/feed/"
tags = ["news", "japanese"]

[feeds.asahi-shimbun-headlines]
# More feeds: https://www.asahi.com/information/service/rss.html
url = "https://www.asahi.com/rss/asahi/newsheadlines.rdf"
tags = ["news", "japanese"]
max = 5

[feeds.nhk]
# More feeds: https://www.nhk.or.jp/toppage/rss/index.html
url = "https://www3.nhk.or.jp/rss/news/cat0.xml"
tags = ["news", "japanese"]
max = 5

## Hacking

[feeds.hacking]
feeds = ["hackernews", "ziglang"]

[feeds.hackernews]
url = "https://news.ycombinator.com/rss"
tags = ["hacking"]
exclude-title-words = ["llm", "ai", "hiring"]

[feeds.ziglang]
url = "https://ziglang.org/devlog/index.xml"
tags = ["hacking", "zig"]

[feeds.lobsters]
url = "https://lobste.rs/rss"
tags = ["hacking"]
exclude-title-words = ["llm", "ai", "hiring"]

[feeds.importai]
url = "https://jack-clark.net/feed/"
tags = ["ai"]

[feeds.tldr]
url = "https://tldr.tech/api/rss/tech"
tags = ["tldr", "news", "tech"]

[feeds.tldr-design]
url = "https://tldr.tech/api/rss/design"
tags = ["tldr", "design"]

[feeds.tldr-devops]
url = "https://tldr.tech/api/rss/devops"
tags = ["tldr", "hacking"]

[feeds.tldr-infosec]
url = "https://tldr.tech/api/rss/infosec"
tags = ["tldr", "hacking", "security"]

# [feeds.infosecurity-magazine]
# url = "https://www.infosecurity-magazine.com/rss/news/"
# tags = ["hacking", "security"]

[feeds.suckless]
url = "http://suckless.org/atom.xml"
tags = ["hacking", "releases"]

[feeds.terminal-trove]
url = "https://terminaltrove.com/blog.xml"
tags = ["hacking"]

## Hacking blogs

[feeds.hachha]
url = "https://hachha.dev/blog.feed"
tags = ["blog", "hacking"]

[feeds.old-new-thing]
url = "https://devblogs.microsoft.com/oldnewthing/feed"
tags = ["blog", "hacking"]

[feeds.bennett-meares]
url = "https://bmeares.com/rss/"
tags = ["blog", "hacking"]

[feeds.dave-heinamann]
url = "https://dheinemann.com/atom/"
tags = ["blog", "hacking"]

[feeds.lucidity]
url = "https://ludic.mataroa.blog/rss/"
tags = ["blog", "hacking"]

[feeds.without-boats]
url = "https://without.boats/index.xml"
tags = ["blog", "hacking"]

[feeds.underjord]
url = "https://underjord.io/feed.xml"
tags = ["blog", "hacking"]

[feeds.matthew-strom]
url = "https://matthewstrom.com/feed.xml"
tags = ["blog", "design"]

[feeds.ntietz]
url = "https://www.ntietz.com/atom.xml"
tags = ["blog", "hacking"]

[feeds.matklad]
url = "https://matklad.github.io/feed.xml"
tags = ["blog", "hacking"]

[feeds.slightknack]
url = "https://slightknack.dev/atom.xml"
tags = ["blog", "hacking"]

[feeds.mitchellh]
url = "https://mitchellh.com/feed.xml"
tags = ["blog", "hacking"]

[feeds.erikarow]
url = "https://erikarow.land/combined.xml"
tags = ["blog", "hacking"]

## Technology

[feeds.guardian-technology]
url = "https://www.theguardian.com/us/technology/rss"
tags = ["news", "science", "technology"]

[feeds.verge]
url = "https://www.theverge.com/rss/index.xml"
tags = ["tech"]
exclude-title-words = ["ai", "llm"]

[feeds.conversation-science-tech]
url = "https://theconversation.com/us/technology/articles.atom"
tags = ["news", "science"]

## Japanese

[feeds.matcha]
url = "https://matcha-jp.com/easy/feed"
tags = ["japanese"]

[feeds.nhk-easier]
url = "https://nhkeasier.com/feed/"
tags = ["japanese", "news"]

## Environment & science

[feeds.guardian-environment]
url = "https://www.theguardian.com/us/environment/rss"
tags = ["news"]

[feeds.guardian-science]
url = "https://www.theguardian.com/science/rss"
tags = ["news", "science"]

[feeds.npr-science]
url = "https://feeds.npr.org/1007/rss.xml"
tags = ["news", "science"]

[feeds.npr-climate]
url = "https://feeds.npr.org/1167/rss.xml"
tags = ["news", "science"]

[feeds.inside-climate-news]
url = "https://insideclimatenews.org/feed"
tags = ["news", "science"]

[feeds.nasa-breaking-news]
url = "http://nasa.gov/rss/dyn/breaking_news.rss"
tags = ["news", "science"]

[feeds.talking-climate]
url = "https://www.talkingclimate.ca/feed"
tags = ["news", "science"]

[feeds.conversation-environment-energy]
url = "https://theconversation.com/us/environment/articles.atom"
tags = ["news", "science"]

[feeds.matt-strassler]
url = "https://profmattstrassler.com/feed/"
tags = ["science"]

## Gaming

[feeds.two-stop-bits]
url = "https://twostopbits.com/rss"
tags = ["gaming"]

[feeds.game-dev-city]
url = "http://gamedev.city/rss"
tags = ["hacking", "gaming"]

[feeds.rust-gamedev-wg]
url = "https://gamedev.rs/rss.xml"
tags = ["hacking", "gaming"]

[feeds.itchio-featured]
url = "https://itch.io/feed/featured.xml"
tags = ["gaming"]

[feeds.gaming-on-linux]
url = "https://www.gamingonlinux.com/article_rss.php"
tags = ["gaming"]

## Comics

[feeds.xkcd]
url = "https://xkcd.com/rss.xml"
tags = ["comics"]

## Positive News

[feeds.goodgoodgood]
url = "https://www.goodgoodgood.co/articles/rss.xml"
tags = ["news", "positive"]

[feeds.positive-news]
url = "http://positive.news/rss"
tags = ["news", "positive"]

## Government

[feeds.usa-bills]
url = "https://www.govinfo.gov/rss/bills.xml"
tags = ["gov"]

[feeds.usa-federal-budget]
url = "https://www.govinfo.gov/rss/budget.xml"
tags = ["gov"]

[feeds.sec]
url = "https://www.sec.gov/news/pressreleases.rss"
tags = ["gov", "sec"]

## Other blogs

[feeds.brandonsanderson]
url = "https://www.brandonsanderson.com/blogs/blog/tagged/state-of-the-sanderson.atom"
tags = ["blog", "reading"]

## Entertainment

[feeds.simpleflips]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCiYpKsB66LZsk7s4yhxJqlQ"
tags = ["gaming", "video"]

[feeds.solidjj]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCEq_Dr1GHvnNPQNfgOzhZ8Q"
tags = ["video"]

[feeds.dunkey]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCsvn_Po0SmunchJYOWpOxMg"
tags = ["gaming", "video"]

[feeds.kurzgesagt]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q"
tags = ["video"]

[feeds.hbomberguy]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UClt01z1wHHT7c5lKcU8pxRQ"
tags = ["video", "notify"]

[feeds.clustermint]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCPQGGTbdmv0AsE1XARaOAVA"
tags = ["gaming", "video"]

[feeds.asahilina-yt]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCwkfNQzKwICfPKs6V0ZUFZQ"
tags = ["hacking", "video"]

[feeds.warowl]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCpFcHE36IoySjYj1Rytxyog"
tags = ["gaming", "video"]

[feeds.ign-reviews]
url = "http://feeds.feedburner.com/ign/reviews"
tags = ["gaming"]

[feeds.ign-tech]
url = "http://feeds.feedburner.com/ign/tech-articles"
tags = ["tech", "gaming"]

[feeds.ign-comics]
url = "https://feeds.feedburner.com/ign/comics-articles"
tags = ["gaming", "comics"]
