name = "catppuccin-macchiato"

[palette]
background = "#24273a" # Base
text = "#cad3f5" # Text
action = "#f4dbd6" # Rosewater
accent = "#b8c0e0" # Subtext1
alert = "#eed49f" # Yellow
error = "#ed8796" # Red
info = "#8aadf4" # Blue
success = "#a6da95" # Green
